---
- name: Continuous Lab Saturation Source
  hosts: all
  sources:
    - ansible.eda.url_check:
        urls:
          - "http://13.62.64.189:8000"
        delay: 1
  rules:
    - name: Log Chatty Event to Console
      condition: event.url_check.status == "up"
      action:
        debug:
          msg: "Event received! Connection to EC2 is healthy."
