---
- name: Saturated Control Plane Source
  hosts: all
  sources:
    - ansible.eda.url_check:
        urls:
          - "http://127.0.0.1:8000"  # Target itself locally
        delay: 0.1                  # 10 pings per second (CRITICAL: this floods the Redis queue!)
  rules:
    - name: Flood Queue
      condition: event.url_check is defined
      action:
        debug:
          msg: "Flooding local queue..."
